### ISSUE TITLE
Unhandled exception in Dispatchers.Default

### ISSUE THREAD

**Issue by jobace78** [romaindalichamp/TerminalTabTailor#23]
Hi,

When a terminal is open (usually first time only), IDEA (IntelliJ IDEA 2024.2.3) shows this exception:

```
Unhandled exception in Dispatchers.Default

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#3751,DefaultDispatcher-worker-19,5,main] 1265183949 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#65,AWT-EventQueue-0,6,main] 1890636488
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:172)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:63)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:287)
	at com.intellij.openapi.wm.impl.content.SingleContentSupplier$Companion.getSupplierFrom(SingleContentSupplier.kt:110)
	at com.intellij.openapi.wm.impl.content.SingleContentSupplier$Companion.getSupplierFrom(SingleContentSupplier.kt:107)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.getSupplier(SingleContentLayout.kt:85)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.tryUpdateContentView(SingleContentLayout.kt:102)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.update(SingleContentLayout.kt:73)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:363)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1$1.propertyChange(ToolWindowContentUi.java:121)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at com.intellij.ui.content.impl.ContentImpl.setDisplayName(ContentImpl.java:110)
	at com.terminaltabtailor.manager.TerminalTabNamesManager$Companion.renameNewTab(TerminalTabNamesManager.kt:169)
	at com.terminaltabtailor.manager.TerminalTabNamesManager$Companion.renameNewTab(TerminalTabNamesManager.kt:91)
	at com.terminaltabtailor.manager.TerminalTabNamesManager$Companion$openTabInTerminal$1$1$1$1$1.invokeSuspend(TerminalTabNamesManager.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6debfa94, Dispatchers.Default]

```

**Comment by romaindalichamp** [comment]
Hi jobace78,

Do you have the latest version of the plugin ?

Thank you for creating the issue,

Romain

**Comment by jobace78** [comment]
Hi!

Yes, they are fully updated:

[...]
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Licensed to XXX
Subscription is active until March 10, 2025.
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  project.tree.structure.show.url=false
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.23339.18)
  com.github.leomillon.uuidgenerator (4.5.1)
  de.femtopedia.diffplugin (2.2.0)
  BrowseWordAtCaret (3.0.5)
  org.intellij.plugins.hcl (242.23339.11)
  PythonCore (242.23339.11)
  org.jetbrains.plugins.go-template (242.20224.155)
  com.terminaltabtailor.TerminalTabTailor (1.4.1)
  org.jetbrains.plugins.go (242.23339.11)
  indent-rainbow.indent-rainbow (2.2.0)
  Pythonid (242.23339.11)
  com.intellij.plugin.adernov.powershell (2.7.0)
  com.intellij.ml.llm (242.23339.40)
  pro.bashsupport (4.3.0.242)
  com.atlassian.bitbucket.references (2023.1.301)
  com.majera.intellij.codereview.bitbucket (2024.3.3.242)
  zielu.gitworktree (1.0.9+231)
  org.sonarlint.idea (10.11.0.79648)
  zielu.gittoolbox (600.0.1+242)
Kotlin: 242.23339.11-IJ
[...]

Regards,
 Joan

**Comment by jobace78** [comment]
Hi @romaindalichamp,

Any news on this issue?

Thanks,
 Joan

**Comment by romaindalichamp** [comment]
Hi @jobace78,

I just released a new version (1.4.3) that fixes some SDK-related issues and updates support to Java 21.
This issue no longer seems to occur with IntelliJ 2024.3+.

Could you please update and let me know if the issue persists?

Thanks,
Romain

**Comment by chrismo** [comment]
I subscribed to this issue after experiencing the same problem - I just upgraded and did not have this error upon opening.

RubyMine 2024.3.5
Build #RM-243.26053.19, built on March 13, 2025
...
Runtime version: 21.0.6+8-b631.39 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.4
...
Non-Bundled Plugins:
...
  com.terminaltabtailor.TerminalTabTailor (1.4.3)
...
